export const icons = {
  quiz: "answer-task",
  visitLink: "link-task",
  referralLink: "referral-task",
  suggestion: "suggestion-task",
  followTwitter: "twitter-task",
  mentionTwitter: "twitter-task",
  tweetTwitter: "twitter-task",
  reTweetTwitter: "twitter-task",
  reTweetQuoteTwitter: "twitter-task",
  likeTweetTwitter: "twitter-task",
  commentTweetTwitter: "twitter-task",
  checkSpaceTwitter: "twitter-task",
  joinDiscord: "discord-task",
  roleDiscord: "discord-task",
  joinTelegram: "telegram-task",
  medium: "medium-task",
  email: "suggestion-task",
  partner: "alphaguilty-task",
  multipleSuggestion: "suggestion-task",
  sequence: "",
  watchVideo: "video-task",
  signUp: "alphaguilty-task",
  completedOnboarding: "alphaguilty-task",
  token: "token",
  nft: "nft",
  valueHolder: "token",
  nativeHolder: "coins",
  blockchainUser: "coins",
  dexLiquidityProvider: "emitOnChainEvent",
  daily: "suggestion-task",
  customWebhook: "suggestion-task",
  imageUpload: "imageUpload",
  invite: "referral-task",
  allBridge: "token",
  bridge: "token",
  gitCoin: "gitCoin"
};

export const statusIcons = {
  done: "done-task",
  expired: "expired-task",
  blocked: "blocked-task",
  review: "review-task",
};
