export const constants = {
  algorithm: 'aes-256-ctr',
  maxImageSize: Math.floor(20 * 1024 * 1024),
  authTokenBufferLength: 24,
  authTokenLength: 48,
  autoTokenActiveTime: 600_000,
  twitter: {
    getApiFriendsList: 'https://api.twitter.com/1.1/friends/list.json',
    getApiFriendsIds: 'https://api.twitter.com/1.1/friends/ids.json',
    getApiUserTimeline: 'https://api.twitter.com/1.1/statuses/user_timeline.json',
    getApiTweetReTweet: 'https://api.twitter.com/1.1/statuses/retweets/',
    getApiTweetStatus: 'https://api.twitter.com/1.1/statuses/show.json',
    getApiTweetSearch: 'https://api.twitter.com/1.1/search/tweets.json',
    getApiTweetData: 'https://api.twitter.com/2/tweets',
    oauthRedirectLink: 'https://api.twitter.com/oauth/authorize',
    oauthRequest: 'https://twitter.com/oauth/request_token',
    oauthAccess: 'https://twitter.com/oauth/access_token',
    authorizeUrl: 'https://twitter.com/i/oauth2/authorize',
    getTokenUrl: 'https://api.twitter.com/2/oauth2/token',
    getApiUserUrl: 'https://api.twitter.com/2/users/',
    getApiTweetUrl: 'https://api.twitter.com/2/tweets/',
    scope: 'offline.access%20tweet.read%20users.read%20follows.read',
  },
  discord: {
    oauthTokenUrl: 'https://discord.com/api/oauth2/token',
    grandType: 'authorization_code',
    getApiUrl: 'https://discord.com/api/',
  },
  botometer: {
    checkUrl: 'https://botometer-pro.p.rapidapi.com/4/check_account',
  },
  defaultAQtoken: { symbol: 'AQ', name: 'AlphaQuest' },
  google: {
    authScope: ['https://www.googleapis.com/auth/userinfo.profile', 'https://www.googleapis.com/auth/userinfo.email'],
    getApiUserInfo: 'https://www.googleapis.com/oauth2/v1/userinfo',
    rootUrl: 'https://accounts.google.com/o/oauth2/v2/auth',
    fetchToken: 'https://oauth2.googleapis.com/token',
  },
};
