export type IButtonType =
  | "primary"
  | "colorfull"
  | "colorfull-error"
  | "secondary"
  | "outlined"
  | "ghost"
  | "link"
  | "w-primary"
  | "checked"
  | "checked-disabled"
  | "error"
  | "task"
  | "store"
  | "icon"
  | "roundedColorfull";
